elasticsearch:
  image: elasticsearch:1.7
  ports:
    - "9200:9200"
    - "9300:9300"
kibana:
  image: kibana:4.1
  ports:
    - "5601:5601"
  links:
    - elasticsearch
logstash:
  image: logstash:1.5
  command: logstash -f /etc/logstash/conf.d/syslog.conf
  environment:
    - LOGSPOUT=ignore
  volumes:
    - $PWD/logstash/config:/etc/logstash/conf.d
  ports:
    - "5000:5000"
  links:
    - elasticsearch
logspout:
  image: gliderlabs/logspout
  command:  syslog://logstash:5000
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
  links:
    - logstash
  environment:
    - LOGSPOUT=ignore